### ISSUE TITLE
Building mesh from a single polygon

### ISSUE THREAD

**Issue by solusipse** [mikewesthad/navmesh#5]
It seems to that if you have a complicated polygon, you have to subdivide it first - am I correct here?
Let's take an example from the readme file:
```
    +-----+-----+
    |     |     |
    |  1  |  2  |
    |     |     |
    +-----------+
          |     |
          |  3  |
          |     |
          +-----+
```

If we want to go from (0,0) to (10,20), such path will be produced:
`{ x: 0, y: 0 }, { x: 10, y: 10 }, { x: 10, y: 20 }`.

Let's modify this case so we have just one complex polygon:
```
   a             b
    +-----------+
    |           |
    |           |
    |           |
    +-----+     |
   f     e|     |
          | x   |
          |     |
          +-----+
         d       c
```

Let's say we want to go from (0,0) to x=(12,15).

```
const polygon = [
    { x: 0,  y: 0  }, //a
    { x: 20, y: 0  }, //b
    { x: 20, y: 20 }, //c
    { x: 10, y: 20 }, //d
    { x: 10, y: 10 }, //e
    { x: 0,  y: 10 }  //f
];
const nm = new NavMesh([polygon]);
const path = nm.findPath({ x: 0, y: 0 }, { x: 12, y: 15 });
```

When I run this, path seems to contain just two points: `{x: 0, y: 0}, {x: 12, y: 15}`, so my question is: am I doing something wrong or maybe navmesh can work only on already subdivided polygons? If that's the case - are there any plans to add mechanism to do that to your awesome library?

Cheers

**Comment by mikewesthad** [comment]
hi @solusipse - you aren't doing anything wrong, it's a limit of the current library. That type of polygon is concave, which is a more complicated beast.

There are libraries like [poly-decom.js](https://github.com/schteppe/poly-decomp.js/) for decomposing a concave polygon into easier to manage convex polygons. It's on the to do list to handle any polygon. The library came about because I needed fast path finding for a game, and the problem that I ran into is that automatically decomposing polygons leads to worse performance than hand-mapping the levels with convex polygons (in my case, specifically rectangles).

I'll add a note to the readme to clarify this. PRs are definitely welcome if you want to wade into this feature.

**Comment by solusipse** [comment]
Great, thank you for the explanation! I think I'll try with that library you shared, thanks for the link.
Btw, I'm sure that you know about path finding much more than me, could you please let me know what you think about approach presented in this article: https://www.david-gouveia.com/pathfinding-on-a-2d-polygonal-map?

**Comment by mikewesthad** [comment]
Sorry this took so long to fix in the readme. Updated it now to warn devs about concave polygons. Hope you got what you were looking for out of that article. Thanks for sharing it. I'll try to read it when I have a few minutes.
