### ISSUE TITLE
NavMesh.destroy enters a infinitie loop

### ISSUE THREAD

**Issue by GGAlanSmithee** [mikewesthad/navmesh#6]
Calling `NavMhes.destroy` will enter an infinite loop, I think the offending lines are:

1. [phaser-navmesh.js line 195](https://github.com/mikewesthad/navmesh/blob/master/packages/phaser-navmesh/src/phaser-navmesh.js#L195) which invokes
2. [phaser-navmesh-plugin.js line 67](https://github.com/mikewesthad/navmesh/blob/master/packages/phaser-navmesh/src/phaser-navmesh-plugin.js#L67), which invokes 
3. [phaser-navmesh-plugin.js line 69](https://github.com/mikewesthad/navmesh/blob/master/packages/phaser-navmesh/src/phaser-navmesh-plugin.js#L69), which in turn invoked function at step 1

Commenting out the function invokation at point 3 ([this line](https://github.com/mikewesthad/navmesh/blob/master/packages/phaser-navmesh/src/phaser-navmesh-plugin.js#L69)), solves this problem, but I do not know if it has any side-effects.

**Comment by GGAlanSmithee** [comment]
By the way, I actually encountered this problem while exploring a work-around for dynamically adding navmesh polygons to a mesh which seems to not be possible ATM. Is it? If not, it would make a great addition!

**Comment by mikewesthad** [comment]
Ah, thanks for doing the detective work and reporting this! This definitely looks like a bug. It probably makes sense for `removeMesh` to simply just remove the mesh - no need to destroy the mesh as well.

As for dynamically adding, are you thinking along the lines of destructible walls where you'd want to be able to add or remove polygons mid-game? It might require a bit of recoding so that the calculation can be done without tanking the frame rate, but it does sound like a worthwhile addition. Happy to accept a PR on it.

**Comment by mikewesthad** [comment]
Should be fixed & published now. I'm going to close this issue, but feel free to respond here or open a new issue about dynamic navmeshes.

**Comment by GGAlanSmithee** [comment]
@mikewesthad Thanks for the quick fix, it works as intended!

Regarding dynamically manipulating the navmesh, my usecase is building a live editor, but another scenario would be for example a RTS, where if you add a building, that spot should be removed (a hole should be added). This feature is supported by [recast.js](https://github.com/vincent/recast.js) for example.

If I get the time, I will look into sending you a PR, not sure I have the velocity to inject myself into another project at the moment though :)
