### ISSUE TITLE
NavMesh breaks when run on server due to umd target

### ISSUE THREAD

**Issue by will-hart** [mikewesthad/navmesh#8]
For a server authoritative game I'm running path finding on the server. When included in a `node` application, the `navmesh` library fails due to [a `window` variable](https://github.com/mikewesthad/navmesh/blob/master/packages/navmesh/dist/navmesh.js#L10) in the built `navmesh` library. 

Changing the `umd` libraryTarget to `commonjs2` on [this line](https://github.com/mikewesthad/navmesh/blob/master/packages/navmesh/webpack.config.js#L20) and rebuilding the library resolved this issue - see [this fork](https://github.com/will-hart/navmesh/tree/commonjs2). 

The tests and examples all run without error, but I'm not expert enough in libraryTargets to know what effect this might have on other applications.

**Comment by mikewesthad** [comment]
@will-hart - thanks! I'll take a look. I don't think we want to target `commonjs2` since `umd` should, in theory, be a more expansive target that works for more environments. I think one of the other options in the webpack config must be off if `umd` is trying to access the `window` under node environments.

**Comment by will-hart** [comment]
Yep, that's why I didn't submit a PR :)

Sounds like this might be an unresolved webpack issue: https://github.com/webpack/webpack/issues/6522, with a possible workaround https://github.com/webpack/webpack/issues/6522#issuecomment-371120689

**Comment by mikewesthad** [comment]
Yeah, that seems right to me. Thanks for digging into it. 

Looking through that, some of the issue in webpack appears to be that in an es module context `this` is undefined, so that shim won't work in an es module. That said, I'm guessing it's better to add a separate build for es module contexts sometime in the future (no need for the boilerplate UMD loader code in that context).

For now, updating the webpack config with that `globalTarget` is the right move. I'll get that in there with a simple node example this week.

**Comment by mikewesthad** [comment]
Thanks for the help in tracking down a solution - navmesh should working on node now.
